version: '3.1'
services: 
  db: 
    image: postgres:latest
    container_name: postgres 
    environment: 
      - POSTGRES_PASSWORD=password 
      - POSTGRES_USER=username 
      - POSTGRES_DB=userview 
    command: " 
              postgres 
                -c max_connections=200 
                -c logging_collector=on 
                -c log_min_messages=LOG 
                -c log_directory=/var/log/postgresql" 
    ports: 
      - 5432:5432 
    volumes: 
      - ./data/postgres-data:/var/lib/postgresql/data 
      - ./logs/postgres:/var/log/postgresql